import { CircleAlert, ShieldCheck } from "lucide-react";

export const businesses = [
  // Hotels
  {
    name: "Hotel Nahargarh Haveli",
    type: "Hotel",
    id: "RJ-HTL-30210",
    place: "Amer Road, Jaipur",
    region: "Amer",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "hotel",
    lat: 26.9535,
    lng: 75.8513,
  },
  {
    name: "The Lalit Jaipur",
    type: "Hotel",
    id: "RJ-HTL-30455",
    place: "Civil Lines, Jaipur",
    region: "Jaipur South",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "hotel",
    lat: 26.9196,
    lng: 75.7878,
  },
  {
    name: "Raj Palace Heritage",
    type: "Hotel",
    id: "RJ-HTL-30782",
    place: "Chomu House, Jaipur",
    region: "Jaipur North",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "hotel",
    lat: 26.9260,
    lng: 75.8050,
  },
  {
    name: "Sunrise Guest House",
    type: "Guest House",
    id: "RJ-GH-41120",
    place: "MI Road, Jaipur",
    region: "Jaipur East",
    status: "Unverified",
    color: "bg-rose-100 text-rose-700",
    category: "hotel",
    lat: 26.9157,
    lng: 75.8005,
  },

  // Restaurants
  {
    name: "Saffron Courtyard",
    type: "Restaurant",
    id: "RJ-FNB-88190",
    place: "Bapu Bazaar, Jaipur",
    region: "Jaipur South",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "restaurant",
    lat: 26.9120,
    lng: 75.8010,
  },
  {
    name: "Laxmi Mishthan Bhandar (LMB)",
    type: "Restaurant",
    id: "RJ-FNB-88023",
    place: "Johari Bazaar, Jaipur",
    region: "Jaipur East",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "restaurant",
    lat: 26.9218,
    lng: 75.8082,
  },
  {
    name: "Chokhi Dhani",
    type: "Restaurant & Cultural Village",
    id: "RJ-FNB-88340",
    place: "Tonk Road, Jaipur",
    region: "Jaipur South",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "restaurant",
    lat: 26.8100,
    lng: 75.8200,
  },
  {
    name: "Highway Dhaba 99",
    type: "Restaurant",
    id: "RJ-FNB-88999",
    place: "NH-48, Jaipur",
    region: "Jaipur West",
    status: "Unverified",
    color: "bg-rose-100 text-rose-700",
    category: "restaurant",
    lat: 26.8450,
    lng: 75.7300,
  },

  // Guides
  {
    name: "Aravalli Heritage Walks",
    type: "Licensed Tourist Guide",
    id: "RJ-GUIDE-20481",
    place: "Amber Fort, Jaipur",
    region: "Amer",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "guide",
    lat: 26.9855,
    lng: 75.8513,
  },
  {
    name: "Rajesh Kumar — Govt. Guide",
    type: "Licensed Tourist Guide",
    id: "RJ-GUIDE-20115",
    place: "Hawa Mahal, Jaipur",
    region: "Jaipur East",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "guide",
    lat: 26.9239,
    lng: 75.8267,
  },
  {
    name: "Fort Explorers Jaipur",
    type: "Licensed Tourist Guide",
    id: "RJ-GUIDE-20390",
    place: "Nahargarh Fort, Jaipur",
    region: "Jaipur North",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "guide",
    lat: 26.9388,
    lng: 75.8156,
  },

  // Tour Operators & Transport
  {
    name: "Pink City Cab Services",
    type: "Tour Operator",
    id: "RJ-TOUR-10732",
    place: "Jaipur",
    region: "Jaipur West",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "transport",
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    name: "Royal Rajasthan Travels",
    type: "Tour Operator",
    id: "RJ-TOUR-10540",
    place: "Station Road, Jaipur",
    region: "Jaipur North",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "transport",
    lat: 26.9196,
    lng: 75.7880,
  },
  {
    name: "Quick Ride Auto",
    type: "Auto Rickshaw Service",
    id: "RJ-TOUR-10998",
    place: "Sindhi Camp, Jaipur",
    region: "Jaipur West",
    status: "Unverified",
    color: "bg-rose-100 text-rose-700",
    category: "transport",
    lat: 26.9220,
    lng: 75.7860,
  },

  // Shops
  {
    name: "Gem Palace",
    type: "Handicraft & Jewellery",
    id: "RJ-SHOP-50120",
    place: "MI Road, Jaipur",
    region: "Jaipur South",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "shop",
    lat: 26.9155,
    lng: 75.8010,
  },
  {
    name: "Anokhi Museum Shop",
    type: "Handicraft Store",
    id: "RJ-SHOP-50245",
    place: "Amber, Jaipur",
    region: "Amer",
    status: "Verified",
    color: "bg-teal-100 text-teal-700",
    category: "shop",
    lat: 26.9830,
    lng: 75.8490,
  },
];

export const advisories = [
  {
    title: "Amber Fort visitor guidance",
    text: "Use only authorised guides and request a printed or digital bill.",
    icon: ShieldCheck,
  },
  {
    title: "Festival crowd advisory",
    text: "Keep valuables secure and use official taxi stands after 8 PM.",
    icon: CircleAlert,
  },
  {
    title: "Beware of fake gem shops",
    text: "Purchase gemstones only from government-certified dealers with a valid GST bill.",
    icon: CircleAlert,
  },
  {
    title: "Auto-rickshaw fare guidance",
    text: "Always insist on the meter or agree on a fare before starting. Use prepaid auto counters at stations.",
    icon: ShieldCheck,
  },
];
